# Generated by Django 2.2 on 2019-05-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20190520_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
