# Generated by Django 2.2 on 2019-06-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0008_auto_20190524_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
