# Generated by Django 2.2 on 2019-06-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0009_auto_20190603_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='address_book.Person', unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='address_book.Person', unique=True),
        ),
    ]
