# Generated by Django 2.2 on 2019-06-03 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0011_auto_20190603_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=70, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
