# Generated by Django 2.2 on 2019-06-03 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0013_auto_20190603_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]$', 'Akceptowane są tylko cyfry')]),
        ),
    ]
