# Generated by Django 2.2 on 2019-06-04 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0015_auto_20190604_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Akceptowane są tylko cyfry', regex='^[0-9]*$')]),
        ),
    ]
