# Generated by Django 2.2 on 2019-06-04 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0016_auto_20190604_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=70, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
